// <auto-generated />
using System;
using HeroAgency.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeroAgency.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeroAgency.Domain.Entities.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SuperHeroes", (string)null);
                });

            modelBuilder.Entity("HeroAgency.Domain.Entities.SuperHeroPower", b =>
                {
                    b.Property<int>("SuperHeroId")
                        .HasColumnType("integer");

                    b.Property<int>("SuperPowerId")
                        .HasColumnType("integer");

                    b.HasKey("SuperHeroId", "SuperPowerId");

                    b.HasIndex("SuperPowerId");

                    b.ToTable("SuperHeroPowers", (string)null);
                });

            modelBuilder.Entity("HeroAgency.Domain.Entities.SuperPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SuperPowers", (string)null);
                });

            modelBuilder.Entity("HeroAgency.Domain.Entities.SuperHeroPower", b =>
                {
                    b.HasOne("HeroAgency.Domain.Entities.SuperHero", "SuperHero")
                        .WithMany("SuperHeroPowers")
                        .HasForeignKey("SuperHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroAgency.Domain.Entities.SuperPower", "SuperPower")
                        .WithMany("SuperHeroPowers")
                        .HasForeignKey("SuperPowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperHero");

                    b.Navigation("SuperPower");
                });

            modelBuilder.Entity("HeroAgency.Domain.Entities.SuperHero", b =>
                {
                    b.Navigation("SuperHeroPowers");
                });

            modelBuilder.Entity("HeroAgency.Domain.Entities.SuperPower", b =>
                {
                    b.Navigation("SuperHeroPowers");
                });
#pragma warning restore 612, 618
        }
    }
}
